-- MySQL Script generated by MySQL Workbench
-- 08/15/16 18:24:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema patrilon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema patrilon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `patrilon` DEFAULT CHARACTER SET utf8 ;
USE `patrilon` ;

-- -----------------------------------------------------
-- Table `patrilon`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrilon`.`Category` ;

CREATE TABLE IF NOT EXISTS `patrilon`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patrilon`.`Page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrilon`.`Page` ;

CREATE TABLE IF NOT EXISTS `patrilon`.`Page` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `countryName` VARCHAR(45) NOT NULL,
  `lat` FLOAT NOT NULL,
  `lng` FLOAT NOT NULL,
  `zoom` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `currency` VARCHAR(45) NOT NULL,
  `nation` VARCHAR(45) NOT NULL,
  `capital` VARCHAR(45) NOT NULL,
  `Category_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Page_Category_idx` (`Category_id` ASC),
  CONSTRAINT `fk_Page_Category`
    FOREIGN KEY (`Category_id`)
    REFERENCES `patrilon`.`Category` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patrilon`.`PhotoCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrilon`.`PhotoCategory` ;

CREATE TABLE IF NOT EXISTS `patrilon`.`PhotoCategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patrilon`.`Photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrilon`.`Photo` ;

CREATE TABLE IF NOT EXISTS `patrilon`.`Photo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `desc` TEXT(64) NOT NULL,
  `photoUrl` VARCHAR(45) NOT NULL,
  `Page_id` INT NOT NULL,
  `PhotoCategory_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idPhoto_UNIQUE` (`id` ASC),
  INDEX `fk_Photo_Page1_idx` (`Page_id` ASC),
  INDEX `fk_Photo_PhotoCategory1_idx` (`PhotoCategory_id` ASC),
  CONSTRAINT `fk_Photo_Page1`
    FOREIGN KEY (`Page_id`)
    REFERENCES `patrilon`.`Page` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Photo_PhotoCategory1`
    FOREIGN KEY (`PhotoCategory_id`)
    REFERENCES `patrilon`.`PhotoCategory` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patrilon`.`Slides`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrilon`.`Slides` ;

CREATE TABLE IF NOT EXISTS `patrilon`.`Slides` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `picUrl` VARCHAR(45) NULL,
  `Page_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Slides_Page1_idx` (`Page_id` ASC),
  CONSTRAINT `fk_Slides_Page1`
    FOREIGN KEY (`Page_id`)
    REFERENCES `patrilon`.`Page` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patrilon`.`mediaData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrilon`.`mediaData` ;

CREATE TABLE IF NOT EXISTS `patrilon`.`mediaData` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `presidentPhoto` VARCHAR(45) NULL,
  `countryGerb` VARCHAR(45) NULL,
  `countryFlag` VARCHAR(45) NULL,
  `Page_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mediaData_Page1_idx` (`Page_id` ASC),
  CONSTRAINT `fk_mediaData_Page1`
    FOREIGN KEY (`Page_id`)
    REFERENCES `patrilon`.`Page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
